---
collections:
  - name: ansible.posix
    version: ">=1.4,<2.0"
  - name: community.general
    version: ">=6.1,<7.0"
  - name: amazon.aws
    version: ">=5.1,<6.0"
  - name: community.aws
    version: ">=5.1,<6.0"
  - name: community.docker
    version: ">=3.3,<4.0"
