---
semaphore_image_repo: flaudisio/bootcamp-semaphore
semaphore_image_tag: "2.8.77"

semaphore_install_dir: /opt/semaphore-docker
semaphore_volume_base_dir: /srv/semaphore-docker

semaphore_port: 3000

semaphore_credentials_ssm_enabled: false
semaphore_credentials_ssm_region: us-east-1

semaphore_postgres_db_name: semaphore
semaphore_postgres_db_user: semaphore
semaphore_postgres_db_pass: ChangeMe!123
semaphore_access_key_encryption: RL0bX8n9hCFRmRZw+qAfvj6kYanrpI3481ZkpcQqe4I=

semaphore_admin_username: admin
semaphore_admin_password: ChangeMe!123
semaphore_admin_name: Semaphore Admin
semaphore_admin_email: admin@example.com
semaphore_web_root: http://semaphore.example.com:3000

semaphore_postgres_image: postgres:14-alpine
