---
- name: Install script
  ansible.builtin.copy:
    src: ansible-run.sh
    dest: /usr/local/bin/ansible-run
    owner: root
    group: root
    mode: 0755
  tags: ansible-run:install

- name: Configure cron environment variables
  ansible.builtin.cron:
    env: true
    name: PATH
    job: "/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin"
    user: root
    cron_file: ansible-run
    state: present
  tags: ansible-run:cron

- name: Configure ansible-run cron job
  ansible.builtin.cron:
    name: ansible-run
    minute: "*/30"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    user: root
    job: ansible-run
    cron_file: ansible-run
    state: present
  tags: ansible-run:cron
