---
- name: Install packages
  ansible.builtin.apt:
    name: "{{ base_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  tags: base:packages

- name: Install prune-docker-images script
  ansible.builtin.copy:
    src: prune-docker-images.sh
    dest: "{{ base_prune_docker_images_path }}"
    owner: root
    group: root
    mode: 0755
  tags: base:prune-docker-images

- name: Configure cron environment variables
  ansible.builtin.cron:
    env: true
    name: PATH
    job: /usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
    user: root
    cron_file: prune-docker-images
    state: present
  tags: base:prune-docker-images

- name: Configure prune-docker-images cron job
  ansible.builtin.cron:
    name: prune-docker-images
    minute: "15"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    user: root
    job: >
      prune-docker-images >> /var/log/prune-docker-images.log 2>&1
    cron_file: prune-docker-images
    state: present
  tags: base:prune-docker-images
