---
nomad_version: 1.5.1

nomad_bin_path: /usr/local/bin/nomad

nomad_user: nomad

nomad_config_dir: /etc/nomad.d
nomad_config_file: "{{ nomad_config_dir }}/nomad.hcl"
nomad_data_dir: /var/opt/nomad
nomad_service_file: /etc/systemd/system/nomad.service

nomad_region: rg1
nomad_datacenter: dc1

nomad_use_consul: false
nomad_consul_address: 127.0.0.1:8500

nomad_node_name: ""
nomad_enable_server: false
nomad_enable_client: false

nomad_bootstrap_expect: 1

nomad_ui_enabled: false

nomad_server_join_hosts:
  - 127.0.0.1

nomad_server_join_retry_max: 3
nomad_server_join_retry_interval: 15s

nomad_client_cni_path: "{{ nomad_cni_plugins_current_dir }}/bin"
nomad_client_cni_config_dir: "{{ nomad_cni_plugins_current_dir }}/config"

# CNI plugins

nomad_install_cni_plugins: false

nomad_cni_plugins_version: 1.2.0

nomad_cni_plugins_dl_base_dir: /opt/cni/{{ nomad_cni_plugins_version }}
nomad_cni_plugins_dl_bin_dir: "{{ nomad_cni_plugins_dl_base_dir }}/bin"
nomad_cni_plugins_current_dir: /opt/cni/current
