---
- name: Ensure nomad user group exists
  ansible.builtin.group:
    name: "{{ _nomad_user }}"
    system: true
    state: present

- name: Ensure nomad user exists
  ansible.builtin.user:
    name: "{{ _nomad_user }}"
    group: "{{ _nomad_user }}"
    system: true
    shell: /usr/sbin/nologin
    state: present

- name: Create server config file
  ansible.builtin.template:
    src: server.hcl.j2
    dest: "{{ nomad_server_config_file }}"
    owner: root
    group: root
    mode: 0644
  notify: Restart Nomad
