---
- name: Ensure Nomad user group exists
  ansible.builtin.group:
    name: "{{ _nomad_user }}"
    system: true
    state: present

- name: Ensure Nomad user exists
  ansible.builtin.user:
    name: "{{ _nomad_user }}"
    group: "{{ _nomad_user }}"
    system: true
    shell: /usr/sbin/nologin
    state: present
