---
- name: Ensure installation directory exists
  ansible.builtin.file:
    path: "{{ semaphore_install_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: semaphore:install

- name: Ensure base data directory exists
  ansible.builtin.file:
    path: "{{ semaphore_volume_base_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0700
  tags: semaphore:install

- name: Include Postgres S3 restore tasks
  ansible.builtin.import_tasks: postgres-s3-restore.yml
  when: semaphore_postgres_s3_restore_enabled | bool
  tags: semaphore:postgres-s3-restore

- name: Create the Docker Compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ semaphore_install_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0600
  tags: semaphore:config

- name: Ensure containers are running
  community.docker.docker_compose:
    project_name: semaphore
    project_src: "{{ semaphore_install_dir }}"
    state: present
  tags: semaphore:service
