---
- name: Ensure Postgres S3 restore directory exists
  ansible.builtin.file:
    path: "{{ semaphore_postgres_s3_restore_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: List available backup files in the S3 bucket
  amazon.aws.s3_object:
    bucket: "{{ semaphore_postgres_s3_backup_bucket }}"
    mode: list
  register: semaphore_postgres_s3_restore_list

- name: Set variable with the latest available Postgres backup file
  ansible.builtin.set_fact:
    semaphore_postgres_s3_restore_file: "{{ semaphore_postgres_s3_restore_list.s3_keys | sort | last }}"

- name: Copy backup file to Postgres S3 restore directory
  amazon.aws.s3_object:
    bucket: "{{ semaphore_postgres_s3_backup_bucket }}"
    object: "{{ semaphore_postgres_s3_restore_file }}"
    dest: "{{ semaphore_postgres_s3_restore_dir }}/{{ semaphore_postgres_s3_restore_file }}"
    mode: get
