---
- name: Install package
  ansible.builtin.apt:
    name: wireguard
    state: present
    update_cache: true
    cache_valid_time: 3600
  tags: wireguard:install

- name: Check if configuration file exists
  ansible.builtin.stat:
    path: "{{ wireguard_config_file }}"
  register: wireguard_config_stat
  tags: wireguard:config

- name: Check if configuration is managed by WG Portal
  ansible.builtin.shell: >
    grep -q -- '-WGP-' '{{ wireguard_config_file }}' ; echo $?
  changed_when: false
  register: wireguard_config_grep
  tags: wireguard:config

- name: Determine if configuration should be changed
  ansible.builtin.set_fact:
    wireguard_manage_config: "{{ (not wireguard_config_stat.stat.exists) or (wireguard_config_grep.stdout == '1') }}"
  tags: wireguard:config

- name: Run configuration tasks
  ansible.builtin.include_tasks: configuration.yml
  when: wireguard_manage_config

- name: Configure IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    sysctl_file: /etc/sysctl.d/90-wireguard.conf
    reload: true
  when: wireguard_enable_ip_forward
  tags: wireguard:sysctl
