---
- name: Debug variables
  hosts: all

  # Inspired by https://gryzli.info/2017/12/21/ansible-debug-print-variables/
  tasks:
    - name: Dump 'vars' variable
      ansible.builtin.debug:
        msg: "{{ vars | to_nice_yaml(indent=2) }}"
      tags: debug:vars

    - name: Dump 'environment' variable
      ansible.builtin.debug:
        msg: "{{ environment | to_nice_yaml(indent=2) }}"
      tags: debug:environment

    - name: Dump 'group_names' variable
      ansible.builtin.debug:
        msg: "{{ group_names | to_nice_yaml(indent=2) }}"
      tags: debug:group_names

    - name: Dump 'groups' variable
      ansible.builtin.debug:
        msg: "{{ groups | to_nice_yaml(indent=2) }}"
      tags: debug:groups

    - name: Dump 'hostvars' variable
      ansible.builtin.debug:
        msg: "{{ hostvars | to_nice_yaml(indent=2) }}"
      tags: debug:hostvars
