---
- name: Deploy WireGuard server
  hosts: all

  roles:
    - role: base
      tags: [base]
    - role: wireguard
      tags: [wireguard]
    - role: wg-portal
      tags: [wg-portal]
    - role: caddy
      tags: [caddy]
