---
- name: Deploy Nomad clients
  hosts: all

  roles:
    - role: base
      tags: [base]
    - role: docker
      tags: [docker]
    - role: consul
      tags: [consul]
    - role: nomad
      tags: [nomad]
