---
# Helper vars for readability
_ssm_region: us-east-1
_ssm_cluster_path: "{{ tags['ansible:ssm-cluster-path'] }}"

consul_node_name: "{{ instance_id }}"
consul_node_type: server

consul_server_ui_enabled: true

consul_server_bootstrap_expect: 3

consul_gossip_key: "{{ lookup('amazon.aws.aws_ssm', _ssm_cluster_path + '/gossip-key', region=_ssm_region) }}"

consul_enable_tls: false

consul_tls_ca_cert_material: "{{ lookup('amazon.aws.aws_ssm', _ssm_cluster_path + '/ca-cert', region=_ssm_region) }}"
consul_tls_ca_key_material: "{{ lookup('amazon.aws.aws_ssm', _ssm_cluster_path + '/ca-key', region=_ssm_region) }}"
