---
# ------------------------------------------------------------------------------
# consul
# ------------------------------------------------------------------------------

consul_node_type: client
consul_client_addr: 127.0.0.1

consul_gossip_key: "{{ lookup('amazon.aws.aws_ssm', '/consul/consul-01/gossip-key', region='us-east-1') }}"

consul_enable_tls: false

# ------------------------------------------------------------------------------
# nomad
# ------------------------------------------------------------------------------

nomad_region: aws-us-east-1
nomad_datacenter: dc1

nomad_node_name: "{{ instance_id }}"
nomad_enable_server: true

nomad_ui_enabled: true

nomad_use_consul: true

# nomad_server_join_hosts:
#   - provider=aws region=us-east-1 addr_type=private_v4 tag_key=service-name tag_value=nomad-01-servers

nomad_bootstrap_expect: 3
