---
# ------------------------------------------------------------------------------
# firewall
# ------------------------------------------------------------------------------

firewall_allowed_tcp_ports:
  - 22
  - 80
  - 443

firewall_allowed_udp_ports:
  - "{{ wireguard_port }}"

firewall_additional_rules:
  - iptables -t nat -A POSTROUTING -o {{ ansible_default_ipv4.interface }} -j MASQUERADE

# ------------------------------------------------------------------------------
# wireguard
# ------------------------------------------------------------------------------

wireguard_address: 10.8.0.1/24

# ------------------------------------------------------------------------------
# wg-portal
# ------------------------------------------------------------------------------

wg_portal_listening_address: 127.0.0.1:8123
wg_portal_external_url: https://vpn.dev.bootcamp.flaudisio.com
wg_portal_website_title: Bootcamp VPN
wg_portal_company_name: Bootcamp
wg_portal_admin_user: flaudisio+bootcamp@gmail.com
wg_portal_admin_pass_ssm_parameter_enabled: true
wg_portal_admin_pass_ssm_parameter_name: /wireguard/wg-portal-admin-password
wg_portal_admin_pass_ssm_parameter_region: us-east-1

# ------------------------------------------------------------------------------
# caddy
# ------------------------------------------------------------------------------

caddy_config: |
  https://vpn.dev.bootcamp.flaudisio.com {
    reverse_proxy localhost:8123
  }
